#!/bin/bash 

echo > "$HOME/tmp/filematches-hack" #clear log file for fresh output
echo "Script requires full directory paths to process. Ex: /home/username/Desktop"
read -r -p "Enter path of source directory. Press enter for the current directory: " sourced
#val="$(echo "$sourced")" 
if [[ -z "$sourced" ]] || [[ "$sourced" == "." ]]; then 
    sourceval="."
elif [[ -d "$sourced" ]]; then 
    sourceval="$sourced"
elif pushd "$sourced" >/dev/null 2>&1; then
    sourceval="$(pwd)"
    popd || return  
else 
    echo No directory matches your input 
    echo Invalid entry - exiting script 
    exit 1 
fi
read -r -p "Enter the target path to find matching files " target

if [[ -d "$target" ]]; then 
    targetval="$target"
else
    echo No directory matches your input 
    echo Invalid entry- exiting script 
    exit 1 
fi
TEMPDIR="$(mktemp /tmp/tmpfile-XXXX)"  
#TEMPSED="$(mktemp /tmp/tmpfile-XXXX)"
#echo name of file sorting tempdir: "$TEMPSED"

trap 'rm -- "$TEMPDIR"' EXIT 

find "$sourceval"  -type f  | awk -F/ '{print $NF}' | tee -a "$TEMPDIR" > /dev/null 

#sed -i 's/^\*$/d'  "$TEMPDIR" "$TEMPSED"

cat "$TEMPDIR"

read -r -p "Go over list of located files if needed. Try vim $TEMPDIR in another window. Continue - yes or no: " ready
if [[ "$ready" == "yes" ]]; then 
    echo "good - let's try to locate files "
    if [[ "$sourceval" == "." ]]; then  
        echo "searching for files on $PWD that are also on $target"
    else
        echo "searching for files on $sourceval that are also on $target"
    fi
    cat "$TEMPDIR" |  while IFS= read -r item 
do  
    search=$(find "$targetval" -iname "*$item*" >> "$HOME/tmp/filematches-hack") #>> "$HOME/tmp/filematches-hack"
    if [[ -n "$search" ]]; then 
        echo no item found matching string: "$item" 
    fi
done  
fi
logout=$(cat "$HOME/tmp/filematches-hack" | wc -l) 
sleep 1s && wait 
if [[ $logout -gt 0 ]]; then
    echo =========================================
    cat "$HOME/tmp/filematches-hack" 
    echo =========================================
    echo all of the files above were found in both directories 
    echo "you can find a log of that here: $HOME/tmp/filematches-hack" 
fi
