#!/bin/bash
#This is a cool little helper script I wrote to help folks find packages - rather than using apt and grep each time along with recalling the syntax to do so 

searchagain() {
    apt list | grep "$1"
}

if [[ -z "$1" ]] || [[ "$1" == "-h" ]]; then 
    echo Script requires at least one argument 
    echo "Ex: 'searchinstalls wine' will search for the wine package" 
elif [[ -n "$1" ]] && ! [[ "$1" == "-h" ]]; then 
    echo "Searching to see if package is installed..." 
    sleep 1s 
    searchvar=$(apt list --installed | grep "$1") 
        if [[ -n "$searchvar" ]]; then 
            echo Found packages. Results: 
            echo "$searchvar" 
            echo        "=====================================================================================" 
            read -r -p  "Did you find what you're looking for? Enter 'yes' or 'no' to search for more packages: " ans
                if [[ "$ans" == "no" ]]; then 
                    if [[ -n $(searchagain "$@") ]]; then 
                        echo "Ok - searching for more packages" 
                        sleep 1s
                        echo "Found packages. Results:" 
                        searchagain "$@" 
                    fi
                else                   
                    echo OK: exiting script now
                    exit 0  
               fi  
      fi
fi 
