#!/bin/bash 

#This is a cool little helper script I wrote to help folks find packages - rather than using apt and grep each time along with recalling the syntax to do so

searchagain() {
    apt list | grep "$1"
}

if [[ -z "$1" ]] || [[ "$1" == "-h" ]]; then
    echo "Script requires at least one argument"
    echo "Ex: 'searchinstalls wine' will search for the wine package"
fi

if [[ -n "$1" ]] && [[ ! "$1" == "-h" ]]; then
    echo "Searching to see if the package is installed..."
    echo Results:      
    sudo apt list --installed | grep "$1" 
    echo "Finished searching"
    echo "====================================================================================="
    read -r -p "Are you satisfied with the results? Enter 'yes' or 'no' to search for available packages: " ans
        if [[ "$ans" == "yes" ]]; then 
        echo OK - exiting script 
        elif [[ "$ans" == "no" ]]; then
            searchresult=$(searchagain "$@")
            if [[ -n "$searchresult" ]]; then
                echo "Found packages. Results:"
                echo "$searchresult"
            else
                echo "Try altering your search for another item"
            fi
        else
            echo "Ok - searching for more packages"
            sleep 1s
            echo "Found packages. Results:"
            searchagain "$@"
            exit 0  
        fi
    fi
